name: Build VEHGuardian DLL

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1️⃣ 检出仓库源码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ 安装 CMake
      - name: Setup CMake
        uses: lukka/get-cmake@v3

      # 3️⃣ 配置 CMake（生成工程）
      - name: Configure CMake
        run: |
          cmake -S . -B build -G "Visual Studio 17 2022" -A x64 -DCMAKE_BUILD_TYPE=Release

      # 4️⃣ 编译项目
      - name: Build project
        run: |
          cmake --build build --config Release --parallel

      # 5️⃣ 上传编译好的 DLL 作为构建产物
      - name: Upload VEHGuardian.dll
        uses: actions/upload-artifact@v4
        with:
          name: VEHGuardian-DLL
          path: build/bin/Release/VEHGuardian.dll
