name: Build and Test DLL

on:
  push:
    branches:
      - main  # 仅在推送到 main 分支时触发构建
  pull_request:
    branches:
      - main  # 仅在 PR 合并到 main 分支时触发构建

jobs:
  build:
    runs-on: windows-latest  # 使用 Windows 环境进行构建

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # 检出代码到构建环境

      - name: Set up CMake
        uses: actions/setup-cmake@v2  # 使用最新版的 CMake 动作

      - name: Set up Visual Studio
        uses: microsoft/setup-msbuild@v1  # 设置 MSBuild 和 Visual Studio 编译器

      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release -S .  # 配置 CMake，指定构建目录和构建类型

      - name: Build with CMake
        run: cmake --build build --config Release  # 使用 CMake 构建项目
